config/routes.rb
Rails.application.routes.draw do
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create, :index]
  root 'posts#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

	before_create :create_remember_token

	validates :password, presence: true, length: { minimum: 6 }
	has_secure_password

	has_many :posts

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper 

#  def sign_in(user)
 # 	remember_token = User.new_remember_token
  #	cookies.permanent[:remember_token] = remember_token
 # 	user.update_attribute(:remember_token, User.digest(remember_token))
 # 	self.current_user = user
 # end

#  def current_user
#  	remember_token = User.digest(cookies[:remember_token])
#  	@current_user ||= User.find_by(remember_token: remember_token)
#  end

#  def current_user=(user)
#  	@current_user = user
#  end

#  def sign_out
#  	current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
#  	cookies[:remember_token] = nil
#  end

  def signed_in_user
    unless signed_in?
      flash.now[:error] = "You must be signed in."
      redirect_to signin_url
    end
  end

#  def signed_in?
#    !@current_user.nil?
#  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :signed_in_user, only: [:new, :create]

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(post_params)
		@post.update_attribute(:foreign_key, current_user.id)
		redirect_to root_path
	end

	def index
		@posts = Post.all
	end

	private

		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:session][:email].downcase)
  	if @user && @user.authenticate(params[:session][:password])
  		flash[:success] = "#{@user.name} is now signed in."
  		sign_in @user
      redirect_to root_path
  	else
  		flash.now[:error] = "Invalid email/password combination."
  		render 'new'
  	end
  end

  def destroy
  	sign_out
    flash[:success] = "You have been signed out."
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  	def sign_in(user)
  		remember_token = User.new_remember_token
  		cookies.permanent[:remember_token] = remember_token
  		user.update_attribute(:remember_token, User.digest(remember_token))
  		self.current_user = user
	end

  def current_user
  	remember_token = User.digest(cookies[:remember_token])
  	@current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
  	@current_user = user
  end

  def sign_out
  	current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
  	cookies[:remember_token] = nil
  end

	def signed_in?
		!current_user.nil?
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if signed_in? %>
      <%= link_to "Create post", new_post_path %>
  		<%= link_to "Sign out", signout_path, method: :delete %>
  	<% else %>
      <%= link_to "Sign in", signin_path %>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% @posts.each do |post| %>
	<p>
		<strong><%= post.title %></strong><br>
		- <%= post.body %>
	</p>
	<% if signed_in? %>
		Author: <%= User.find_by(id: post.foreign_key).name %>
	<% end %>	
<% end %>
<% puts "#{signed_in?}, #{@current_user}" %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title, class: 'form-control' %>
	</p>

	<p>
	<%= f.label :body %><br>
	<%= f.text_area :body %>
	</p>

	<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/static_pages/index.html.erb
<h1>Welcome!</h1>